user_homepage:
    path:     /
    defaults: { _controller: "AppBundle:User:index" }
    methods:  [GET]
    options:
        expose: true
        
user_login_check:
    path:     /login_check
    defaults: { _controller: "AppBundle:User:loginCheck" }
    methods:  [POST]
    options:
        expose: true
        
user_login:
    path:     /take-me-in
    defaults: { _controller: "AppBundle:User:login" }
    methods:  [GET, POST]
    options:
        expose: true
        
user_register:
    path:     /register
    defaults: { _controller: "AppBundle:User:register" }
    methods:  [GET]
    options:
        expose: true
        
user_create:
    path:     /create
    defaults: { _controller: "AppBundle:User:create" }
    methods:  [POST]
    options:
        expose: true